### ISSUE TITLE
About dialog is scaled incorrectly

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/ph-scale#168] opened 2020-07-09 23:02 UTC
**Test device**

Windows 10 laptop

**Operating System**

Windows 10 v.1903

**Browser**

Chrome Version 83.0.4103.116 

**Problem description**

For https://github.com/phetsims/QA/issues/514

The about screen seems to be slightly cut off at the top. Adjusting the size of the screen did not seem to alter or remedy the issue.

**Visuals**

![2020-07-09PHScaleslightlycutoff](https://user-images.githubusercontent.com/54685448/87098933-b2496180-c205-11ea-9151-6283f4f4a5d0.PNG)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪pH Scale‬
URL: https://phet-dev.colorado.edu/html/ph-scale/1.4.0-rc.1/phet/ph-scale_all_phet.html
Version: 1.4.0-rc.1 2020-07-09 22:04:23 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
Language: en-US
Window: 1433x706
Pixel Ratio: 1.3406250476837158/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by pixelzoom** [comment] 2020-07-10 21:00
Reproduced (sort of) on macOS 10.15.5 with Chrome 83. See below with `?dev`. And it seems to be a problem with all browsers.  When the browser window is wider than the ScreenView's layoutBounds, the About dialog is being scaled incorrectly.   

I suspect that this is not specific to AboutDialog, and is likely a problem with scaling of all Dialogs.  We'll need to find out who worked on Dialog most recently, and investigate.   @ariel-phet please prioritize (high?) and assign.

<img width="1047" alt="screenshot_424" src="https://user-images.githubusercontent.com/3046552/87202496-eb450d00-c2bd-11ea-9425-cc2f0b753adc.png">

**Comment by samreid** [comment] 2020-07-10 21:05
Should this block publication?  Should recent RCs with this bug be maintenance released?  Is it related to https://github.com/phetsims/joist/issues/586 ?

**Comment by pixelzoom** [comment] 2020-07-10 21:14
Yes, I think this should block publication of ph-scale and all sims.  Dialogs should stay within the ScreenView layoutBounds.

No idea if it's related to phetsims/joist#586.  That issue has been assigned to me for weeks.  I haven't been involved in Dialog scaling, and it's going to take time that I don't have.  My recommedation is to track down whoever last worked on Dialog scaling and have them work on fixing both issues.

**Comment by pixelzoom** [comment] 2020-07-10 21:18
This problem gets worse as the height of AboutDialog increases.  Here's what ph-scale master looks like with a bunch of lines added to the credits:

<img width="1048" alt="screenshot_427" src="https://user-images.githubusercontent.com/3046552/87203788-948d0280-c2c0-11ea-995d-12946c1717fd.png">

Interesting is that it's handled properly on the Home screen:

<img width="1046" alt="screenshot_428" src="https://user-images.githubusercontent.com/3046552/87203810-a1a9f180-c2c0-11ea-81b7-a051f9ae7fa1.png">

**Comment by pixelzoom** [comment] 2020-07-13 17:11
A workaround was applied in phetsims/joist#639.  It's not a final solution, but @ariel-phet asked for the workaround in order to move ph-scale forward.   In pH Scale, About dialog now fits inside the layoutBounds, see screenshot below. 

<img width="1123" alt="screenshot_429" src="https://user-images.githubusercontent.com/3046552/87332882-870e8d00-c4f9-11ea-9056-feb4388ea292.png">

**Comment by pixelzoom** [comment] 2020-07-14 21:17
I still need to patch this in the release branch.

**Comment by pixelzoom** [comment] 2020-08-04 21:37
To test this in ph-scale 1.4.0-rc.2:

1. Run the sim with `?dev` to display layoutBounds (red rectangle) around screens.
2. Open the About dialog from the PhET, verify that it fits inside the layoutBounds on the home screen and 1 other non-home screen, and that it's the same size in both places.

**Comment by KatieWoe** [comment] 2021-05-12 19:52
Looks ok in 1.5.0-dev.1 on Win 10 Chrome. Closing

**Closed by KatieWoe** 2021-05-12 19:52 UTC
Labels: status:ready-for-qa, type:bug
