### ISSUE TITLE
It's possible to set dropper.positionProperty outside range

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/ph-scale#270] opened 2023-01-18 21:56 UTC
**Test device**
MacBoo Air (m1 chip)

**Operating System**
13.1

**Browser**
safari

**Problem description**
For https://github.com/phetsims/qa/issues/872 and https://github.com/phetsims/qa/issues/873, it is possible to move the dropper outside of range. Once I click on the dropper, it snaps back into place. 

**Steps to reproduce**
Here is an example from pH Scale Basics:
1. Go to phScaleBasics.macroScreen.model.dropper.positionProperty
2. Press Get Value 
3. Change the Value of Y to 150
4. Click on the dropper

**Visuals**

https://user-images.githubusercontent.com/87318828/213302931-815c89c7-bf70-4e7a-88b0-6d640bc9dd25.mp4

**Comment by arouinfar** [comment] 2023-01-19 00:14
Thanks @Nancy-Salpepi. 

This is also true for `pHMeter.probe.positionProperty`. Normally, the pH probe is bounded to the sim's `layoutBounds`. You can see this when running the sim with `?dev` and dragging the probe to the edge of the screen. The probe will stop when it reaches the edge of the `layoutBounds` (red line). If you use setValue to set the position outside of this boundary and then click on the probe, it will jump back to the edge of the `layoutBounds`. It seems like the `layoutBounds` do not depend at all on the window size, so maybe we can enforce a range on the `positionProperty`? Even if we cannot, I am not overly concerned. The sim will not crash if the `positionProperty` is outside of the visible bounds of the sim, and it can always be retrieved by returning to the previous position or using Reset All.

In the case of the pH probe, I think it is valuable for clients to be able to reposition it with an API command. This would allow clients to move the probe into/out of the beaker in their wrapper. I do not think the same holds for `dropper.positionProperty`. There is no pedagogical value in being able to move the dropper, and we can add this issue to the list of reasons why having a movable dropper is more trouble than its worth.

@pixelzoom here are my recommendations
* Set `dropper.positionProperty` to `phetioReadOnly: true`. There is no reason for clients to have API control over this.
* If possible, limit `pHMeter.probe.positionProperty` to the `layoutBounds`.

**Comment by pixelzoom** [comment] 2023-01-19 03:30
> * Set dropper.positionProperty to phetioReadOnly: true. There is no reason for clients to have API control over this.

Easy. But I'd much rather make the dropper have a static position, to put an end to the problems that `dropper.positionProperty` has caused.  @arouinfar how do you want to proceed?

> * If possible, limit `pHMeter.probe.positionProperty` to the `layoutBounds`.

Not going to happen -- it's too much work, and does not address this problem generally.  As I said recently or Beer's Law Lab... I'm of the opinion that when there are drag constraints, `positionProperty` should be `phetioReadOnly: true`, and the position should be customized by using the sims.   Setting `positionProperty` via an API call is not something that anyone has asked for, and trying to constrain the position to some bounds in that case is a programming and documentation "can of worms".    @arouinfar do you want me to change `pHMeter.probe.positionProperty` to `phetioReadOnly: true`, or do you want to leave it as is and document the drag bounds in the Client Guide?

**Comment by pixelzoom** [comment] 2023-01-19 03:32
Another thing to note about `dropper.positionProperty` is that only the x coordiante of the position should be changed, because dragging is constrained to be horizontal.  So someone setting `dropper.positionProperty` through the PhET-iO API would need to know that only x can be changed, and they would need to know the allowable range of x.

**Comment by pixelzoom** [comment] 2023-01-19 20:23
My recommendations are:

* Remove the ability to move the dropper. If that's OK, then please go to Studio, place the dropper where you'd like it to appear, and tell me the value of `dropper.positionProperty`.

* Make no code changes for `pHMeter.probe.positionProperty`.  If you feel that's it's necessary (which I do not), document that the drag bounds are `Bounds2( 0, 0, 1100, 700 )`.  And that's `Bounds2( minX, minY, maxX, maxY )`.

**Comment by arouinfar** [comment] 2023-01-20 00:25
> Remove the ability to move the dropper. If that's OK, then please go to Studio, place the dropper where you'd like it to appear, and tell me the value of `dropper.positionProperty`.

Yes, let's do it. We can use the default initial position ` { "x": 700, "y": 265 }` for the permanent position. 

> Make no code changes for `pHMeter.probe.positionProperty`. If you feel that's it's necessary (which I do not), document that `pointProperty.value.x` is constrained to `[0, 1100]`, and y is constrained to `[0, 700]`. Note that this sim has non-default layoutBounds, so it's possible that those constraints could change in the future -- which is a good reason NOT to document them outside of the code.

Sounds reasonable to me. I see value in clients having control of the probe position, but I don't think we need to add documentation that is bound to get stale. Clients can easily get the coordinates from Studio for use in their wrappers later.

**Comment by arouinfar** [comment] 2023-01-20 19:48
For future reference, here's a list of the many issues related to having a movable dropper. 
* https://github.com/phetsims/ph-scale/issues/141
* https://github.com/phetsims/scenery/issues/1041
* https://github.com/phetsims/ph-scale/issues/215
* https://github.com/phetsims/ph-scale/issues/250
* https://github.com/phetsims/ph-scale/issues/252
* https://github.com/phetsims/ph-scale/issues/263

There are probably more that I missed, but this is a pretty good overview of complexities.

**Comment by pixelzoom** [comment] 2023-01-23 16:35
Since https://github.com/phetsims/ph-scale/issues/271 went so poorly due to migration problems, I'm waiting to move forward on this issue until all migration-related issues are resolved and patched.

**Comment by pixelzoom** [comment] 2023-01-23 18:40
I'll address this in master, @samreid @zepumph will cherry-pick.

**Comment by samreid** [comment] 2023-01-27 23:12
@zepumph and I cherry picked the changes and confirmed they work well.  Would be good for @Nancy-Salpepi to double check following the directions in the top comment.

**Comment by zepumph** [comment] 2023-01-28 01:09
Position is not draggable in ph-scale and basics 1.6.0-rc.2. Ready to close after QA verification.

**Comment by Nancy-Salpepi** [comment] 2023-02-04 14:27
The dropper is no longer draggable in pH Scale and pH Scale Basics rc.3 (`model.dropper.positionProperty` and `view.dropperNode.dragListener` have been removed from the tree). Closing!

**Comment by KatieWoe** [comment] 2023-02-06 22:16
Should the position property still be visible due to this from Amy?
>Sounds reasonable to me. I see value in clients having control of the probe position, but I don't think we need to add documentation that is bound to get stale. Clients can easily get the coordinates from Studio for use in their wrappers later.

If I'm misunderstanding please close again.

**Comment by arouinfar** [comment] 2023-02-06 22:51
Thanks for checking @KatieWoe. The comment you quoted was in reference to `phScale.macroScreen.model.pHMeter.probe.positionProperty` (not the dropper). I've confirmed it still exists in rc.3, closing.

**Closed by arouinfar** 2023-02-06 22:51 UTC
Labels: type:bug, status:ready-for-review, design:phet-io
