### ISSUE TITLE
CT Uncaught RangeError: toFixed() digits argument must be between 0 and 100

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ph-scale#286] opened 2023-06-30 20:59 UTC
```
ph-scale : phet-io-studio-fuzz : unbuilt
http://128.138.93.172//continuous-testing/ct-snapshots/1688154842092/studio/?sim=ph-scale&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22ph-scale%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1688154842092%22%2C%22timestamp%22%3A1688155494917%7D
Uncaught RangeError: toFixed() digits argument must be between 0 and 100
RangeError: toFixed() digits argument must be between 0 and 100
at Number.toFixed
at toFixed (Utils.js:556:20)
at toFixed (Utils.js:572:29)
at toFixedNumber (Utils.js:882:17)
at roundToInterval (GraphIndicatorDragListener.ts:99:32)
at doDrag (GraphIndicatorDragListener.ts:62:35)
at _dragListener (PressListener.ts:526:9)
at call (DragListener.ts:296:35)
at apply (PhetioAction.ts:161:16)
at execute (DragListener.ts:447:21)
[URL] http://128.138.93.172//continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1688154842092%2Fstudio%2F%3Fsim%3Dph-scale%26phetioWrapperDebug%3Dtrue%26fuzz&testInfo=%7B%22test%22%3A%5B%22ph-scale%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1688154842092%22%2C%22timestamp%22%3A1688155494917%7D
[NAVIGATED] http://128.138.93.172//continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1688154842092%2Fstudio%2F%3Fsim%3Dph-scale%26phetioWrapperDebug%3Dtrue%26fuzz&testInfo=%7B%22test%22%3A%5B%22ph-scale%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1688154842092%22%2C%22timestamp%22%3A1688155494917%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172//continuous-testing/ct-snapshots/1688154842092/studio/?sim=ph-scale&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22ph-scale%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1688154842092%22%2C%22timestamp%22%3A1688155494917%7D
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172//continuous-testing/ct-snapshots/1688154842092/ph-scale/ph-scale_en.html?brand=phet-io&ea&debugger&postMessageOnError&sim=ph-scale&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22ph-scale%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1688154842092%22%2C%22timestamp%22%3A1688155494917%7D&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false
[CONSOLE] enabling assert
[CONSOLE] continuous-test-wrapper-load
[PAGE ERROR] Error: RangeError: toFixed() digits argument must be between 0 and 100
at Number.toFixed (<anonymous>)
at Object.toFixed (http://128.138.93.172//continuous-testing/ct-snapshots/1688154842092/chipper/dist/js/dot/js/Utils.js:497:21)
at Object.toFixedNumber (http://128.138.93.172//continuous-testing/ct-snapshots/1688154842092/chipper/dist/js/dot/js/Utils.js:513:29)
at Object.roundToInterval (http://128.138.93.172//continuous-testing/ct-snapshots/1688154842092/chipper/dist/js/dot/js/Utils.js:788:18)
at GraphIndicatorDragListener.doDrag (http://128.138.93.172//continuous-testing/ct-snapshots/1688154842092/chipper/dist/js/ph-scale/js/common/view/graph/GraphIndicatorDragListener.js:67:33)
at GraphIndicatorDragListener.drag [as _dragListener] (http://128.138.93.172//continuous-testing/ct-snapshots/1688154842092/chipper/dist/js/ph-scale/js/common/view/graph/GraphIndicatorDragListener.js:41:36)
at GraphIndicatorDragListener.drag (http://128.138.93.172//continuous-testing/ct-snapshots/1688154842092/chipper/dist/js/scenery/js/listeners/PressListener.js:341:10)
at DragListener._dragAction.PhetioAction.parameters.name (http://128.138.93.172//continuous-testing/ct-snapshots/1688154842092/chipper/dist/js/scenery/js/listeners/DragListener.js:166:36)
at PhetioAction.execute (http://128.138.93.172//continuous-testing/ct-snapshots/1688154842092/chipper/dist/js/tandem/js/PhetioAction.js:132:17)
at GraphIndicatorDragListener.drag (http://128.138.93.172//continuous-testing/ct-snapshots/1688154842092/chipper/dist/js/scenery/js/listeners/DragListener.js:299:22)
[PAGE ERROR] Error: RangeError: toFixed() digits argument must be between 0 and 100
at Number.toFixed (<anonymous>)
at Object.toFixed (http://128.138.93.172//continuous-testing/ct-snapshots/1688154842092/chipper/dist/js/dot/js/Utils.js:497:21)
at Object.toFixedNumber (http://128.138.93.172//continuous-testing/ct-snapshots/1688154842092/chipper/dist/js/dot/js/Utils.js:513:29)
at Object.roundToInterval (http://128.138.93.172//continuous-testing/ct-snapshots/1688154842092/chipper/dist/js/dot/js/Utils.js:788:18)
at GraphIndicatorDragListener.doDrag (http://128.138.93.172//continuous-testing/ct-snapshots/1688154842092/chipper/dist/js/ph-scale/js/common/view/graph/GraphIndicatorDragListener.js:67:33)
at GraphIndicatorDragListener.drag [as _dragListener] (http://128.138.93.172//continuous-testing/ct-snapshots/1688154842092/chipper/dist/js/ph-scale/js/common/view/graph/GraphIndicatorDragListener.js:41:36)
at GraphIndicatorDragListener.drag (http://128.138.93.172//continuous-testing/ct-snapshots/1688154842092/chipper/dist/js/scenery/js/listeners/PressListener.js:341:10)
at DragListener._dragAction.PhetioAction.parameters.name (http://128.138.93.172//continuous-testing/ct-snapshots/1688154842092/chipper/dist/js/scenery/js/listeners/DragListener.js:166:36)
at PhetioAction.execute (http://128.138.93.172//continuous-testing/ct-snapshots/1688154842092/chipper/dist/js/tandem/js/PhetioAction.js:132:17)
at GraphIndicatorDragListener.drag (http://128.138.93.172//continuous-testing/ct-snapshots/1688154842092/chipper/dist/js/scenery/js/listeners/DragListener.js:299:22)
[CONSOLE] continuous-test-wrapper-error

id: "Sparky Node Puppeteer"
Snapshot from 6/30/2023, 1:54:02 PM
```

**Comment by pixelzoom** [comment] 2023-07-02 19:17
This started occurring 6/29/23 @ 10:57:40am, and it has been occurring regularly (but not always) since then.  It's manifesting in the "ph-scale : phet-io-studio-fuzz : unbuilt" test.

@zepumph were any new CT tests added/enabled around this time?

**Comment by pixelzoom** [comment] 2023-07-06 00:09
To reproduce manually in master:

1. Go to the My Solution screen.
2. Drag either the H<sub>3</sub>O<sup>+</sup> or OH<sup>-</sup> indicator on the graph.

To see what the value is that is causin the RangeError, make this change to Utils.toFixed:

```diff
  toFixed( value, decimalPlaces ) {
    const multiplier = Math.pow( 10, decimalPlaces );
    const newValue = Utils.roundSymmetric( value * multiplier ) / multiplier;
+   assert && assert( decimalPlaces >= 0 && decimalPlaces <= 20, `decimalPlaces is out of range for Number.toFixed: ${decimalPlaces}` );
    return newValue.toFixed( decimalPlaces ); // eslint-disable-line bad-sim-text
  },
```

I see console output:

> decimalPlaces is out of range for Number.toFixed: 21

**Comment by pixelzoom** [comment] 2023-07-06 00:42
I'm a bit stumped on this one.  No idea why this suddenly started occurring on 6/29, and there have been no recent changes to the sim. 

Is it possible that the JavaScript API for `Number.toFixed` changed, and now only supports 20 decimal places?

**Comment by zepumph** [comment] 2023-07-06 16:22
FYI I believe this was newly reported because of a bug fix in our wrapper fuzz test reporting over in https://github.com/phetsims/phet-io/issues/1944 (https://github.com/phetsims/phet-io-wrappers/commit/7f61e79389b0654f17f7f5fdedd4f0d9a3adf9b6). Studio should be reporting its errors better on CT since last week.

**Comment by pixelzoom** [comment] 2023-07-06 22:19
Also confusing is that the error from `Number.toFixed` indicates that its parameter range is 0-100:

> RangeError: toFixed() digits argument must be between 0 and 100

While the doc in lib.es5.d.ts indicates that its parameter range is 0-20:

```ts
    /**
     * Returns a string representing a number in fixed-point notation.
     * @param fractionDigits Number of digits after the decimal point. Must be in the range 0 - 20, inclusive.
     */
    toFixed(fractionDigits?: number): string;
```

Is it possible that TypeScript 5.1 is somehow the problem here?  PhET upgraded to 5.1.3 on 6/5/23.

**Comment by pixelzoom** [comment] 2023-07-06 22:27
Yesterday I could reproduce manually in master using the steps in https://github.com/phetsims/ph-scale/issues/286#issuecomment-1622714279.  Today I cannot reproduce.  Weird!!

**Comment by pixelzoom** [comment] 2023-07-06 22:55
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Precision_range# says:
> The JavaScript exception "precision is out of range" occurs when a number that's outside of the range of 0 and 20 (or 21) was passed into `toFixed` or `toPrecision`.

So confused... Why does the CT RangeError say "between 0 and 100" ?!?

**Comment by pixelzoom** [comment] 2023-07-06 23:00
Testing in Chrome 114 verifies that `Number.toFixed` has a range of [0,100] for its first argument: 

```
> (123).toFixed( 0 )
'123'
> (123).toFixed( 20 )
'123.00000000000000000000'
> (123).toFixed( 21 )
'123.000000000000000000000'
> (123).toFixed( 100 )
'123.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
> (123).toFixed( 101 )
VM1131:1 Uncaught RangeError: toFixed() digits argument must be between 0 and 100
    at Number.toFixed (<anonymous>)
    at eval (eval at <anonymous> (ph-scale_en.html:1:7), <anonymous>:1:7)
    at Number.toFixed (<anonymous>)
    at <anonymous>:1:7
> (123).toFixed( -1 )
VM1165:1 Uncaught RangeError: toFixed() digits argument must be between 0 and 100
    at Number.toFixed (<anonymous>)
    at eval (eval at <anonymous> (ph-scale_en.html:1:7), <anonymous>:1:7)
    at Number.toFixed (<anonymous>)
    at <anonymous>:1:7
```

**Comment by pixelzoom** [comment] 2023-07-06 23:15
CT (sparky) is apparently also running TypeScript 5.1.6:

> % node /data/share/phet/continuous-testing/ct-main/chipper/node_modules/typescript/bin/tsc --version
Version 5.1.6

**Comment by pixelzoom** [comment] 2023-07-06 23:26
There are apparently 4 subdirectories on CT, each with their own copies of repos and version of TypeScript:

```
% ls -l /data/share/phet/continuous-testing
total 48
drwxrwxr-x. 194 phet phet 8192 May 8 12:34 ct-browser-clients
drwxrwxr-x. 197 phet phet 8192 May 10 12:00 ct-main
drwxr-xr-x. 195 phet phet 8192 May 10 12:00 ct-node-client
drwxrwxr-x. 195 phet phet 8192 May 3 17:10 ct-quick
```

2 of them are stale:

ct-browser-clients -> 5.0.4
ct-main -> 5.1.6
ct-node-client -> 5.0.4
ct-quick -> 5.1.6

Which one of these is running the test that's failing here? 

It sure would be nice if [continuous-testing-management.md](https://github.com/phetsims/aqua/blob/master/doc/continuous-testing-management.md) described these subdirectories in one place. There are breadcrumbs spread throughout that doc.  ct-quick is never mentioned, but I can guess.

**Comment by pixelzoom** [comment] 2023-07-07 18:03
I asked in Slack#developer, but have not yet received a reply.  I'm wondering:

* Is it significant that there are stale versions of TypeScript on CT?
* Is it OK to `npm update` for the stale versions?
* Which CT subdirectory is responsible for running the test that's failing in this issue?

**Comment by zepumph** [comment] 2023-07-07 20:52
I updated some doc above to try to make things clearer. I'm kind confused how we got on the Typescript version, since the error is being reported from a browser test. My best guess is that the current version of Puppeteer (aqua/package reports ~19.2.2) may be causing this issue, since both @pixelzoom and I cannot reproduce it in our browsers.

In fact, if you just use the exact link reported in the error, my browser doesn't find the issue. I'll need to keep thinking about this, but won't have time today.

**Comment by pixelzoom** [comment] 2023-07-07 20:58
> I'm kind confused how we got on the Typescript version, since the error is being reported from a browser test. 

I started looking at TypeScript version because lib.es5.d.ts says the range for `Number.toFixed` is "0 - 20 inclusive", and the sim is failing with value 21. Meanwhile, testing in the browser (see https://github.com/phetsims/ph-scale/issues/286#issuecomment-1624411093) clearly shows that the range is [0,100].  So I was wondering if there was some TypeScript transpilarion hackery going on that was changing the behavior of `Number.toFixed`.

**Comment by pixelzoom** [comment] 2023-07-07 21:15
Since I was able to reproduce this locally on 7/5 (see https://github.com/phetsims/ph-scale/issues/286#issuecomment-1622714279), I hypothesized that I may have upgraded TypeScript since then.   So I tried rolling back to TypeScript 5.1.3 (see steps below), to see if I could reproduce.  I could not. 

1. Change chipper/package.json to `"typescript": "5.1.3"`
2. Delete chipper/node_modules/ and chipper/dist/
3. Run `cd chipper; npm install`
4. Run `tsc --version` to confirm that I have 5.1.3
5. Run `transpile.js --watch` to rebuild chipper/dist/

**Comment by pixelzoom** [comment] 2023-07-08 00:35
@zepumph tried doing manual `npm update` + `rm dist/` for chipper on CT, hoping that would clear things up. It did not, and the error persists.

To add to the confusion, here's the man page for RangeError: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Precision_range

> The JavaScript exception "precision is out of range" occurs when a number that's outside of the range of 0 and 20 (or 21) was passed into toFixed or toPrecision.
> ...
> RangeError: toFixed() digits argument must be between 0 and 100 (V8-based & Safari)

Again, the same inconsistency --- how can the range be both [0,20] and [0,100] ??

**Comment by pixelzoom** [comment] 2023-07-08 00:42
In the above commit, I temporarily changed the implementation of Utils.toFixed:

```diff
  toFixed( value, decimalPlaces ) {
    const multiplier = Math.pow( 10, decimalPlaces );
    const newValue = Utils.roundSymmetric( value * multiplier ) / multiplier;
-     return  newValue.toFixed( decimalPlaces ); // eslint-disable-line bad-sim-text
- }
+    let fixedValue;
+    try {
+      fixedValue = newValue.toFixed( decimalPlaces ); // eslint-disable-line bad-sim-text
+    }
+    catch( error ) {
+      //TODO https://github.com/phetsims/ph-scale/issues/286 This is temporary, for debugging with CT.
+      throw new Error( `Number.toFixed failed: message=${error.message}, fractionDigits=${decimalPlaces}` );
+    }
+    return fixedValue;
+  },
```

The goal here is to see what value is causing the CT failure.  I anticipate that it will be 21.

**Comment by pixelzoom** [comment] 2023-07-08 01:10
How disappointing :) I was expecting 21. But the failing value in this case is 107.

> ph-scale : phet-io-studio-fuzz : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1688777160129/studio/?sim=ph-scale&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22ph-scale%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1688777160129%22%2C%22timestamp%22%3A1688777929505%7D
Uncaught Error: Number.toFixed failed: message=toFixed() digits argument must be between 0 and 100, fractionDigits=107
Error: Number.toFixed failed: message=toFixed() digits argument must be between 0 and 100, fractionDigits=107
at (Utils.js:562:12)
at toFixed (Utils.js:580:29)
at toFixedNumber (Utils.js:890:17)
at roundToInterval (GraphIndicatorDragListener.ts:99:32)
at doDrag (GraphIndicatorDragListener.ts:62:35)
at _dragListener (PressListener.ts:526:9)
at call (DragListener.ts:296:35)
at apply (PhetioAction.ts:161:16)
at execute (DragListener.ts:447:21)
at drag (PressListener.ts:897:13)
id: Sparky Puppeteer
Snapshot from 7/7/2023, 6:46:00 PM

**Comment by pixelzoom** [comment] 2023-07-08 13:41
I reverted the change to Util.toFixed.

I also understand why I was able to reproduce this previous in https://github.com/phetsims/ph-scale/issues/286#issuecomment-1622714279.  In those steps, I had added this assertion to Util.toFixed:

```diff
+   assert && assert( decimalPlaces >= 0 && decimalPlaces <= 20, `decimalPlaces is out of range for Number.toFixed: ${decimalPlaces}` );
```

So CT is failing with values out the range [0,100].  And I need to figure out why the value is able to get so large for that test, but not when using the sim typically.

**Comment by pixelzoom** [comment] 2023-07-22 15:36
As of 7/22/23, this is still occurring on almost every CT cycle.

**Comment by samreid** [comment] 2023-07-26 23:35
I added an assertion that may help us track down the problem.

**Comment by samreid** [comment] 2023-07-27 00:00
With that assertion, CT triggered this case:

> Uncaught Error: Assertion failed: Number of decimal places: 112, yView: 3182.6201201201197, value: 4.259727887085396e-111, exponent: -112, interval: 1e-112, totalVolume = 0.5, graphUnits = MOLES_PER_LITER

Do the yView or value numbers seem out of bounds?

**Comment by samreid** [comment] 2023-07-27 00:28
You can trigger this error via the following steps:

1. Launch ph-scale (doesn't need studio)
2. Go to the My Solution screen
3. Make the window very tall and thin
4. Drag the H3O+ indicator to the bottom of the screen.

This offset will trigger it:

![image](https://github.com/phetsims/ph-scale/assets/679486/c4b40be4-b5a3-45d9-acc8-bac14cfa03fe)

**Comment by pixelzoom** [comment] 2023-07-27 16:47
Thanks @samreid, https://github.com/phetsims/ph-scale/issues/286#issuecomment-1652725090 is very useful.  I had tried that previously, but apparently need to make the window even taller and narrowerer.  I'm able to produce in my working copy, and I'll address it.  But it's an unlikely scenario, and I'm wondering why CT is testing with a browser window that has this aspet ratio.

**Comment by pixelzoom** [comment] 2023-07-27 18:34
Fixed in the above commit by limiting dragging to the height of the layoutBounds.  Relevant change in GraphIndicatorDragListener.ts:

```diff
+       // Prevent downstream RangeError in Number.toFixed. See https://github.com/phetsims/ph-scale/issues/286
+       const yPointer = Math.min( graphIndicatorNode.globalToParentPoint( event.pointer.point ).y,
+         PHScaleConstants.SCREEN_VIEW_OPTIONS.layoutBounds.height );

        // Adjust the y-coordinate for the offset between the pointer and the indicator's origin
-       const yView = graphIndicatorNode.globalToParentPoint( event.pointer.point ).y - clickYOffset;
+       const yView = yPointer - clickYOffset;
```

I'll leave this open for a few CT cycles, to make sure it's resolved.

**Comment by pixelzoom** [comment] 2023-07-27 20:10
CT is happy, so closing.

**Closed by pixelzoom** 2023-07-27 20:10 UTC
Labels: dev:phet-io, type:automated-testing, status:blocks-sim-publication
