### ISSUE TITLE
Draining solution leaves graphics artifacts

### ISSUE THREAD

**Issue by etwa4650** [phetsims/ph-scale#81] opened 2019-05-29 18:01 UTC
CM edit: For phetsims/QA#323 and phetsims/QA#326.

<b>Test Device</b>

DIRAC

  <b>Operating System</b>

10.11.6

  <b>Browser</b>

Firefox 67.0

  <b>Problem Description</b>
In the Legends of Learning environment,
When draining out a substance of the "Macro" screen, some lines of the substance color remain displayed even after the substance has drained past that point.

I could only replicate this on the "Macro" screen

Existed in the published version as well

  <b>Steps to Reproduce</b>

 1: In LoL, go to the "Macro" Screen
 2: Select "Hand Soap" (does not matter but its most visible)
 3: Fill the container with Hand Soap
 4: Drain the container 

  <b>Visuals</b>

https://drive.google.com/open?id=1vdbYUSqqGz0X99YkQL3t5VE8g9lTDsZL

**Comment by pixelzoom** [comment] 2019-05-29 21:10
I don't see this with Firefox 67.0 on macOS 11.14.5 (latest).  So it's probably platform specific.  

@etwa4650 please identify the supported platforms that this occurs on.

**Comment by etwa4650** [comment] 2019-05-30 15:46
@pixelzoom 

I was able to replicate on:

Mac 10.10.5 & Firefox 67.0
Mac 10.11.6 & Firefox 67.0
Mac 10.12.6 & Firefox 67.0
Windows 7 & Firefox 67.0
Windows 10  v1809 & Firefox 67.0 (effect is much less noticeable)


Unable to reproduce on any other browser
Unable to reproduce on IOS or Mac OS 10.13 and up

**Comment by pixelzoom** [comment] 2019-05-30 16:04
Thanks @etwa4650.

**Comment by etwa4650** [comment] 2019-05-30 17:10
@pixelzoom 

I just was able to replicate this on the JORDAN device which runs Mac 10.13.6 and on Firefox 67.0

When I first tested Mac OS 10.13.6 it was on my personal computer.

They both have the same OS and have Firefox 67.0 so maybe this is a hardware issue.

**Comment by pixelzoom** [comment] 2019-05-30 17:44
Thanks @etwa4650. Excellent sleuthing.

**Comment by pixelzoom** [comment] 2019-05-30 18:40
This is yet-another Firefox-specific redraw problem.  @jonathanolson could you please suggest how to best address this?

**Comment by pixelzoom** [comment] 2019-05-31 01:18
@etwa4650 I just noticed that the title and description both say "in LoL".   Is LoL required to reproduce this, or do you also see it when running without LoL?

**Comment by etwa4650** [comment] 2019-05-31 02:10
@pixelzoom It only happens in LoL, sorry if that wasn't clear

**Comment by pixelzoom** [comment] 2019-06-01 19:33
@etwa4650 you were plenty clear, I just read your report too quickly.  Thanks for the clarification.

**Comment by pixelzoom** [comment] 2019-06-01 19:38
For phetsims/QA#323 and phetsims/QA#326.

**Comment by jonathanolson** [comment] 2019-06-03 21:18
Probably best addressed by a transparent rectangle floating at the top of the "liquid", so that it hopefully forces a repaint during draining.

**Comment by pixelzoom** [comment] 2019-06-04 15:44
@jonathanolson thoughts on why this is happening only in the LoL harness?

**Comment by jonathanolson** [comment] 2019-06-04 17:31
> @jonathanolson thoughts on why this is happening only in the LoL harness?

Very likely to just be the size of the sim being slightly smaller. Resizing the window would likely have the same effect (although the iframe may contribute).

**Comment by pixelzoom** [comment] 2019-06-04 21:21
@etwa4650 the hypothesis in https://github.com/phetsims/ph-scale/issues/81#issuecomment-498768177 is that this isn't dependent on the LoL harness, but is dependent on browser window size.  Would you have some time to try to reproduce this outside of the LoL harness, by resizing the browser window?

**Comment by etwa4650** [comment] 2019-06-05 17:23
@pixelzoom 
I was unable to reproduce the issue outside of LoL even with a very small browser window.

Additionally, the issue still exists in LoL with the browser window in full screen.

**Comment by pixelzoom** [comment] 2019-06-16 03:37
I was able to reproduce this on macOS 10.14.5 (latest) with Firefox 67.0.2 (latest).  I loaded pH Scale into the LoL harness, then resizes the browser window until I saw the problem.  See screenshot below.  As soon as I released the mouse, the screen redrew and the lines disappeared.  So I think this is specific to Firefox and independent of macOS version. 

<img width="1440" alt="screenshot_1251" src="https://user-images.githubusercontent.com/3046552/59558715-9ac58800-8fb5-11e9-86b3-fe2261d53264.png">

**Comment by pixelzoom** [comment] 2019-06-16 03:51
@jonathanolson said:
> Probably best addressed by a transparent rectangle floating at the top of the "liquid", so that it hopefully forces a repaint during draining.

@jonathanolson do you think a transparent rectangle that fills the beaker, placed behind the solution in the beaker, would also force a repaint?

**Comment by pixelzoom** [comment] 2019-06-17 01:34
I asked:
> @jonathanolson do you think a transparent rectangle that fills the beaker, placed behind the solution ("liquid") in the beaker, would also force a repaint? 

I answered the question myself by trying this. The answer is no.

**Comment by pixelzoom** [comment] 2019-06-17 01:47
@jonathanolson suggested:
> Probably best addressed by a transparent rectangle floating at the top of the "liquid", so that it hopefully forces a repaint during draining.

I tried this approach in the patch below.  It also did not work.   Even if it did work, this seems like a workaround that we'd potentially need to apply wherever anything is moving.  So it doesn't seem wise to be working around it like this, we should be investigating a general solution in scenery.

@ariel-phet We'll need some of @jonathanolson's time to address this.  Please prioritize and assign.

<details>
<summary>Patch</summary>
```
Index: js/common/view/SolutionNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/SolutionNode.js	(revision f7afb6a0329d943b75ce4dfb2ea8b025743fd139)
+++ js/common/view/SolutionNode.js	(date 1560735874000)
@@ -11,6 +11,7 @@
 
   // modules
   var inherit = require( 'PHET_CORE/inherit' );
+  var Node = require( 'SCENERY/nodes/Node' );
   var phScale = require( 'PH_SCALE/phScale' );
   var PHScaleConstants = require( 'PH_SCALE/common/PHScaleConstants' );
   var Rectangle = require( 'SCENERY/nodes/Rectangle' );
@@ -24,25 +25,33 @@
    */
   function SolutionNode( solution, beaker, modelViewTransform ) {
 
-    var self = this;
+    var viewLocation = modelViewTransform.modelToViewPosition( beaker.location );
+    var viewWidth = modelViewTransform.modelToViewDeltaX( beaker.size.width );
 
-    Rectangle.call( this, 0, 0, 1, 1, { lineWidth: 1 } ); // size and color set dynamically
+    // size and color set dynamically
+    var solutionRectangle = new Rectangle( 0, 0, 1, 1, {
+      lineWidth: 1
+    } );
+
+    // transparent rectangle above the solution, to address graphics artifact on FireFox,
+    // see https://github.com/phetsims/ph-scale/issues/81
+    var transparentRectangle = new Rectangle( 0, 0, viewWidth, 10, {
+      fill: 'transparent'
+    } );
 
     /*
      * Updates the color of the solution, accounting for saturation.
      * @param {Color} color
      */
     solution.colorProperty.link( function( color ) {
-      self.fill = color;
-      self.stroke = color.darkerColor();
+      solutionRectangle.fill = color;
+      solutionRectangle.stroke = color.darkerColor();
     } );
 
     /*
      * Updates the amount of stuff in the beaker, based on solution volume.
      * @param {number} volume
      */
-    var viewLocation = modelViewTransform.modelToViewPosition( beaker.location );
-    var viewWidth = modelViewTransform.modelToViewDeltaX( beaker.size.width );
     solution.volumeProperty.link( function( volume ) {
       assert && assert( volume >= 0 );
 
@@ -58,11 +67,19 @@
       var viewHeight = modelViewTransform.modelToViewDeltaY( solutionHeight );
 
       // shape
-      self.setRect( viewLocation.x - (viewWidth / 2), viewLocation.y - viewHeight, viewWidth, viewHeight );
+      solutionRectangle.setRect( viewLocation.x - (viewWidth / 2), viewLocation.y - viewHeight, viewWidth, viewHeight );
+
+      // position the transparent rectangle above the solutions
+      transparentRectangle.left = solutionRectangle.left;
+      transparentRectangle.bottom = solutionRectangle.top + 1;
+    } );
+
+    Node.call( this, {
+       children: [ transparentRectangle, solutionRectangle ]
     } );
   }
 
   phScale.register( 'SolutionNode', SolutionNode );
 
-  return inherit( Rectangle, SolutionNode );
+  return inherit( Node, SolutionNode );
 } );
\ No newline at end of file
```
</details>

**Comment by pixelzoom** [comment] 2019-06-17 01:51
So to summarize:
* This is not specific to LoL, it's reproducible with certain browser window sizes.
* None of the recommended workarounds has worked.
* This seems like a general problem that should be addressed in scenery.

**Comment by jonathanolson** [comment] 2019-06-17 16:06
Things like this keep coming up, so it does sound like a general Scenery workaround (enabled based on the browser/OS/sim combination, since it might reduce performance) would be good.

**Comment by ariel-phet** [comment] 2019-06-19 16:16
FF on Mac is 0.3% of website traffic, I think we might want to just drop FF support on Mac. Will bring up at dev meeting.

**Comment by pixelzoom** [comment] 2019-06-21 13:22
@ariel-phet We should also identify whether this is a problem with FF on Windows. I don't think that's been done yet.

**Comment by ariel-phet** [comment] 2019-06-23 23:47
@etwa4650 @KatieWoe can you see if you can reproduce this problem on FF windows?

**Comment by KatieWoe** [comment] 2019-06-24 14:37
It does.  I checked.  Seen in this issue: https://github.com/phetsims/QA/issues/352#issuecomment-504529605

**Comment by pixelzoom** [comment] 2019-06-26 02:26
Thanks @KatieWoe.  This issue occurs with FF on both macOS and Windows, so dropping FF support on macOS doesn't help us.   Back to @ariel-phet.

**Comment by ariel-phet** [comment] 2019-07-01 17:58
@KatieWoe can you make me a video of this happening on Windows + FF and assign back to me?

**Comment by KatieWoe** [comment] 2019-07-01 18:09
![SVGfirefoxbug](https://user-images.githubusercontent.com/41024075/60457337-008e5280-9bf9-11e9-85c9-db4cf323b67c.gif)

**Comment by ariel-phet** [comment] 2019-07-01 21:13
Thanks @KatieWoe. This is minor enough to ignore on Windows FF. Certainly keep an eye out for things like this in the future. Hopefully firefox will fix things before we need to investigate a general scenery workaround, but I am not willing to invest the resources in that sort of work currently.

Marking as `wontfix` and closings

**Closed** 2019-07-01 21:14 UTC
Labels: type:bug, type:wontfix
