### ISSUE TITLE
Diluted solutions have a different color than published

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ph-scale#147] opened 2020-03-24 19:21 UTC
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/487.
The solutions, when they have been diluted with water, have a different color than the same solutions diluted the same amount in the published version of the sim. In general, the new colors seem to be more green/grey. Milk and spit don't seem to have this problem, at least as noticeably at the amount of dilution tested, likely due to their starting colors.

**Steps To Reproduce**
1. Go to the first screen on both the dev and published sims
2. Select the same solution for both and let them fill to the .5 L line
3. Use the faucet to fill the rest of the bucket fully (1.2 L)
4. Compare

**Visuals**
In comments bellow to make things more manageable.

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪pH Scale‬
URL: https://phet-dev.colorado.edu/html/ph-scale/1.4.0-dev.15/phet/ph-scale_all_phet.html
Version: 1.4.0-dev.15 2020-03-23 21:08:00 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment] 2020-03-24 19:22
Battery Acid Old:
![oldbattery](https://user-images.githubusercontent.com/41024075/77467933-77e0c380-6dd2-11ea-8b1b-3ac2de64e14e.png)
Battery Acid New:
![newbattery](https://user-images.githubusercontent.com/41024075/77467955-7f07d180-6dd2-11ea-808e-81549634bc14.png)

**Comment by KatieWoe** [comment] 2020-03-24 19:23
Blood Old:
![oldblood](https://user-images.githubusercontent.com/41024075/77467987-8cbd5700-6dd2-11ea-99df-f684daddc23f.png)
Blood New:
![newblood](https://user-images.githubusercontent.com/41024075/77468023-9941af80-6dd2-11ea-88b8-55835ae559e9.png)

**Comment by KatieWoe** [comment] 2020-03-24 19:23
Chicken Soup Old:
![oldsoup](https://user-images.githubusercontent.com/41024075/77468062-a9598f00-6dd2-11ea-9c48-4c7fc33c53fb.png)
Chicken Soup New:
![newsoup](https://user-images.githubusercontent.com/41024075/77468074-b2e2f700-6dd2-11ea-8667-26ac774a37d9.png)

**Comment by KatieWoe** [comment] 2020-03-24 19:24
Coffee Old:
![oldcoffee](https://user-images.githubusercontent.com/41024075/77468102-be362280-6dd2-11ea-84b4-6dfaca71dbb1.png)
Coffee New:
![newcoffee](https://user-images.githubusercontent.com/41024075/77468114-c3936d00-6dd2-11ea-9962-e9fe87ae93bf.png)

**Comment by KatieWoe** [comment] 2020-03-24 20:15
This folder has the rest of the examples:
https://drive.google.com/drive/folders/1MglNYToLIO3HMcgpzoYyfRiOg62ibMmS?usp=sharing

**Comment by pixelzoom** [comment] 2020-03-24 20:20
"Old" = [1.3.4](https://phet-dev.colorado.edu/html/ph-scale/1.3.4/phet/ph-scale_all_phet.html)

"New" = [1.4.0-dev.15](https://phet-dev.colorado.edu/html/ph-scale/1.4.0-dev.15/phet/ph-scale_all_phet.html)

**Comment by pixelzoom** [comment] 2020-03-24 20:23
Thanks @KatieWoe.  I've reproduced on Chrome Version 80.0.3987.149 + macOS 10.15.3.  I'll investigate.  Unassigning @arouinfar.

**Comment by pixelzoom** [comment] 2020-03-24 20:39
I'm going to use coffee, for further testing, since this probably seems independent of solute.

The first thing that I did was to compare the colors of water and coffee in master and the 1.3 branch. They are unchanged:

```
// master
PHScaleColors.WATER: new Color( 224, 255, 255 )
Solute.COFFEE.stockColor: new Color( 164, 99, 7 )

// 1.3
PHScaleColors.WATER: new Color( 224, 255, 255 )
Solute.COFFEE.stockColor: new Color( 164, 99, 7 )
```

**Comment by pixelzoom** [comment] 2020-03-24 20:48
The next thing I checked is the implementation of Solute `completeColor`, which computes the color of the solution based on the colors and volumes of solvent (water) and solute.  It looks like this in 1.3 branch:

```js
computeColor: function( ratio ) {
  assert && assert( ratio >= 0 && ratio <= 1 );
  var color;
  if ( this.colorStop ) {
    // solute has an optional color-stop
    if ( ratio > this.colorStop.ratio ) {
      color = Color.interpolateRGBA( this.colorStop.color, this.stockColor, ( ratio - this.colorStop.ratio ) / ( 1 - this.colorStop.ratio) );
    }
    else {
      color = Color.interpolateRGBA( this.dilutedColor, this.colorStop.color, ratio / this.colorStop.ratio );
    }
  }
  else {
    color = Color.interpolateRGBA( this.dilutedColor, this.stockColor, ratio );
  }
  return color;
}
```

In master, there was a change: `this.colorStop.color` is replaced with `this.colorStopColor`, and `this.colorStop.ratio` is replaced with `this.colorStopRatio`.  This was done as part of the creation of `SoluteIO` for https://github.com/phetsims/ph-scale/issues/92, where major changes were made to `Solute` in https://github.com/phetsims/ph-scale/commit/799c136d4aee166c2e946b338968863af3af7ad1.

**Comment by pixelzoom** [comment] 2020-03-24 21:13
The next thing I checked is the implementation of Solute `completeColor`, which computes the color of the solution based on the colors and volumes of solvent (water) and solute.  It looks like this in 1.3 branch:

```js
computeColor: function( ratio ) {
  assert && assert( ratio >= 0 && ratio <= 1 );
  var color;
  if ( this.colorStop ) {
    // solute has an optional color-stop
    if ( ratio > this.colorStop.ratio ) {
      color = Color.interpolateRGBA( this.colorStop.color, this.stockColor, ( ratio - this.colorStop.ratio ) / ( 1 - this.colorStop.ratio) );
    }
    else {
      color = Color.interpolateRGBA( this.dilutedColor, this.colorStop.color, ratio / this.colorStop.ratio );
    }
  }
  else {
    color = Color.interpolateRGBA( this.dilutedColor, this.stockColor, ratio );
  }
  return color;
}
```

In master, there was a change: `this.colorStop.color` is replaced with `this.colorStopColor`, and `this.colorStop.ratio` is replaced with `this.colorStopRatio`.  This was done as part of the creation of SoluteIO for https://github.com/phetsims/ph-scale/issues/92, in https://github.com/phetsims/ph-scale/commit/799c136d4aee166c2e946b338968863af3af7ad1.

**Comment by pixelzoom** [comment] 2020-03-24 21:14
The bug was definitely introduced in https://github.com/phetsims/ph-scale/commit/799c136d4aee166c2e946b338968863af3af7ad1 during PhET-iO instrumentation.  It's fixed in master. @KatieWoe please verify.  If it looks OK, you can close this issue.  And good catch!

**Comment by KatieWoe** [comment] 2020-03-24 21:33
All solutions look good on master

**Comment by pixelzoom** [comment] 2020-03-24 21:36
👍 Closing.

**Closed by pixelzoom** 2020-03-24 21:36 UTC
Labels: status:ready-for-review, type:bug
