### ISSUE TITLE
broken links in wrapper index

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ph-scale#186] opened 2020-07-24 19:28 UTC
For https://github.com/phetsims/QA/issues/514 and https://github.com/phetsims/QA/issues/515. Seen on Win 10 Edge and Chrome. 
When adding `/doc` to the end of the wrapper index, you are now taken to a menu that shows, along with the API documentation of before, a "Phet-io Guide" and a "Client Requests." These links, both from that menu and from the wrapper index seem to be blank. From the doc menu, there also seem to be other options that we may not intend to be accessible.

![aspectsofdocgone](https://user-images.githubusercontent.com/41024075/88428133-83102400-cdb1-11ea-9b01-fd424ec9efe7.gif)

**Comment by pixelzoom** [comment] 2020-07-27 16:43
I'm not sure if this is a general PhET-iO issue, or if it's because ph-scale is missing files.   Assigning to PhET-iO team to investigate.  If this is a general problem, please create a general GitHub issue and link to it here.

**Comment by arouinfar** [comment] 2020-07-27 16:53
I'm pretty sure this is due to #167. The rc was built with empty .md files, and that's why I supplied QA with .pdf guides as an alternative.

@KatieWoe please check the GAO wrapper index page from the latest dev test (https://github.com/phetsims/QA/issues/519) to see if the problem exists there too. That sim had the guides ready before the dev version was built, so it should be behaving normally.

**Comment by KatieWoe** [comment] 2020-07-27 16:55
Ok. They open there. I didn't realize that was what you meant when you posted the pdfs. Sorry.

**Comment by pixelzoom** [comment] 2020-07-27 18:12
So how do we proceed with this issue? Mark it as "fixed-awaiting-deploy" and verify that the links work in the next QA?

**Comment by zepumph** [comment] 2020-07-27 19:56
I recommend closing this issue, as a duplicate of https://github.com/phetsims/ph-scale/issues/167. and to verify that one in the next QA.

**Comment by pixelzoom** [comment] 2020-07-27 20:04
Closing as duplicate of #167.

**Closed by pixelzoom** 2020-07-27 20:04 UTC
Labels: dev:phet-io, type:bug
