### ISSUE TITLE
Mac Firefox: Playback wrapper doesn't work when console is closed

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#161] opened 2020-04-07 23:27 UTC
ph-scale suffers from https://github.com/phetsims/phet-io-wrappers/issues/342 (Mac Firefox: Playback wrapper doesn't work without console open). 

@arouinfar is this a pre-requisite for publishing ph-scale 1.4.0 ?  If so, please provide the iO team with requested priority in that issue.

**Comment by pixelzoom** [comment] 2020-04-07 23:32
This issue is blocked until phetsims/phet-io-wrappers#342 is resolved.

**Comment by pixelzoom** [comment] 2020-04-10 20:05
Over in https://github.com/phetsims/phet-io-wrappers/issues/342#issuecomment-612194563, @zepumph said:
> Until we know more about this, it seems like we should count it as blocking.

Therefore I'm going to label this issue as "blocks-sim-publication".

**Comment by pixelzoom** [comment] 2020-04-10 22:24
Since sim publication is "sooner', raising priority to high.

**Comment by arouinfar** [comment] 2020-04-15 22:18
@kathy-phet says that this issue does not block the dev delivery to the client, but should be addressed before rc.

**Comment by pixelzoom** [comment] 2020-07-08 23:36
Client feedback has been received and we're on the path to a production version. So undeferring this issue.

**Comment by pixelzoom** [comment] 2020-07-08 23:48
In https://github.com/phetsims/phet-io-wrappers/issues/342#issuecomment-655813141, @zepumph said:
> @pixelzoom I think this issue has been fixed, and @KatieWoe has created https://github.com/phetsims/phet-io-wrappers/issues/352 for a second bug found while testing the fix for this one. If you think that that issue should be blocking publication for ph-scale, please mark it as so. Once reading this, please close this issue.

I replied that whether the new issues is blocking is not my call - it's up to designers.  Assigning this issue to @arouinfar to decide whether https://github.com/phetsims/phet-io-wrappers/issues/352 is blocking for this sim.

**Comment by arouinfar** [comment] 2020-07-09 04:08
@KatieWoe has already verified that https://github.com/phetsims/phet-io-wrappers/issues/342 has been fixed.

After great frustration in figuring out how to use the recording and playback wrappers, I was unable to reproduce https://github.com/phetsims/phet-io-wrappers/issues/352 in Mac/Firefox so I wouldn't consider it blocking. I think we can go ahead and close this issue.

**Closed by arouinfar** 2020-07-09 04:08 UTC
Labels: dev:phet-io, status:on-hold, type:bug
