### ISSUE TITLE
Provide clients with links to model.md and Teacher Tips

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#273] opened 2023-01-23 18:17 UTC
In https://github.com/phetsims/phet-io-sim-specific/issues/20#issuecomment-1398722962, @arouinfar said:
> This is relevant to https://github.com/phetsims/qa/issues/872 and https://github.com/phetsims/qa/issues/873. 

This blocks the next RC for ph-scale 1.6 and ph-scale-basics 1.6.

**Comment by samreid** [comment] 2023-01-27 23:25
@zepumph and I also had to adopt changes from https://github.com/phetsims/friction/issues/316, but we took those changes from copySupplementalFiles (not via cherry-pick), and it seems to be working well now.  @zepumph and I will spot check this in RC.2.

**Comment by zepumph** [comment] 2023-01-28 00:29
https://github.com/phetsims/chipper/commit/132fbed90f680f4349a3b066b56d54a0982e3a38 is a great commit, but we didn't add it to ph-scale 1.6 dependencies until https://github.com/phetsims/ph-scale/commit/5e8b708b3c74ea2fbc0ee0232d8d785fdb60e6bf.

**Comment by zepumph** [comment] 2023-01-28 01:08
I confirmed the phet-io guide looks good in ph-scale and basics 1.6.0-rc.2. Closing

**Closed by zepumph** 2023-01-28 01:08 UTC
Labels: status:fixed-awaiting-deploy, status:blocks-sim-publication
