### ISSUE TITLE
Memory leak in Tandem.removePhetioObject

### ISSUE THREAD

**Issue by zepumph** [phetsims/ph-scale#201] opened 2020-08-26 18:57 UTC
This is fixed in master over in https://github.com/phetsims/tandem/issues/203#issuecomment-681061719, but should be cherry-picked into ph-scale branches. 

Please pick over https://github.com/phetsims/tandem/commit/dc10b0352a7650599cd79be48f50c60ef6f328ea.

**Comment by pixelzoom** [comment] 2020-08-26 21:06
Duplicate of #199. Closing.

**Closed by pixelzoom** 2020-08-26 21:06 UTC
