### ISSUE TITLE
home screen buttons don't behave correctly on touch devices

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ph-scale#160] opened 2020-04-07 21:26 UTC
For https://github.com/phetsims/QA/issues/487 Found on Safari 13 iPadOS 13.4, but occurs on any touch screen.
On published sim, when on the home screen you have to tap an icon to make it bigger, then tap again to enter that screen. In this sim, it seems to enter with only one tap and does not make the icon in question bigger.
![pushbutton](https://user-images.githubusercontent.com/41024075/78721099-23fed000-78e4-11ea-9c6c-98c0c0d85527.gif)

Steps:
1. Go to the sim with a touch device
2. Click the second or third screen icon (one of the small ones)

**Comment by pixelzoom** [comment] 2020-04-07 21:30
@KatieWoe what are you trying to show here with the GIF?  Why do I see frames of the Number Line sim? The GIFs are nice, but steps to reproduce are always appreciated.

**Comment by KatieWoe** [comment] 2020-04-07 21:32
The published (Number line) shows normal behavior. pH Scale is in there first, and it shows the bugged behavior.

**Comment by KatieWoe** [comment] 2020-04-07 21:33
Steps added

**Comment by pixelzoom** [comment] 2020-04-07 21:36
Reproduced with [1.0.0-dev.15]() on iOS 13.3.1 + Safari.

And I'm seeing this same problem in master with all sims. 

@KatieWoe which version of Number Line were you demonstrating?

**Comment by KatieWoe** [comment] 2020-04-07 21:36
Published version 1.0.1

**Comment by pixelzoom** [comment] 2020-04-07 21:39
Looks like something is broken in master for all sims.  @KatieWoe can you verify?

**Comment by KatieWoe** [comment] 2020-04-07 21:43
Looks like. Where should this be transferred?

**Comment by pixelzoom** [comment] 2020-04-07 21:49
This is broken for all sims, and is being tracked in https://github.com/phetsims/joist/issues/624.  Blocked until that issue is addressed.

**Comment by pixelzoom** [comment] 2020-04-09 18:33
This was fixed in https://github.com/phetsims/joist/issues/624.  @KatieWoe please verify in master.

**Comment by KatieWoe** [comment] 2020-04-10 15:21
Looks good on master

**Closed** 2020-04-10 16:37 UTC
Labels: status:ready-for-review, type:bug
