### ISSUE TITLE
appending a non-existent locale to standard wrapper does not load

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#274] opened 2023-01-23 18:18 UTC
https://github.com/phetsims/phet-io/issues/1901 is relevant to https://github.com/phetsims/qa/issues/872 and https://github.com/phetsims/qa/issues/873

**Comment by zepumph** [comment] 2023-01-24 20:24
Cherry pick: https://github.com/phetsims/phet-io-wrappers/commit/84da4632b21a7163b3e7922604d2ced29b5d4133

Test: follow steps in the first comment of https://github.com/phetsims/phet-io/issues/1901 and make sure a bad locale will work.

**Comment by samreid** [comment] 2023-01-27 23:28
@zepumph and I cherry-picked the fixes and this is ready for QA verification, following the steps described in https://github.com/phetsims/phet-io/issues/1901.

**Comment by zepumph** [comment] 2023-01-28 01:06
I confirmed in ph-scale and basics 1.6.0-rc.2. QA please feel free to close.

**Comment by Nancy-Salpepi** [comment] 2023-02-06 20:27
Confirming that the standard wrapper opens (bad locale ignored) in ph Scale and ph Scale basics. 
However, https://github.com/phetsims/phet-io/issues/1901#issuecomment-1401423861 says that with phetioDebug=true, I should see an assertion when a bad locale is used and I do not. Neither does @KatieWoe.

**Comment by KatieWoe** [comment] 2023-02-06 20:41
I attempted this on the standalone wrapper, but phetioDebug=true didn't seem to work. Is this expected?
<img width="960" alt="debugnoton" src="https://user-images.githubusercontent.com/41024075/217080543-ef2bc49e-5f48-402b-bfd7-83b6fa0f82a9.png">

**Comment by arouinfar** [comment] 2023-02-06 23:30
@samreid is it possible that https://github.com/phetsims/phet-io-wrappers/commit/84da4632b21a7163b3e7922604d2ced29b5d4133 didn't make it into the 1.6 branch?

**Comment by samreid** [comment] 2023-02-07 00:31
@KatieWoe and I discussed this in a zoom call.  The "standalone wrapper" isn't actually a wrapper and hence doesn't support wrapper query parameters like phetioDebug.

**Comment by arouinfar** [comment] 2023-02-07 00:35
> The "standalone wrapper" isn't actually a wrapper and hence doesn't support wrapper query parameters like phetioDebug.

Oh, I missed that part of @KatieWoe's comment. However, @Nancy-Salpepi is reporting that there isn't an assertion in the Standard PhET-iO Wrapper for a bad locale when `phetioDebug=true`. I tested rc.3 and I'm not seeing an assertion, either.

**Comment by samreid** [comment] 2023-02-07 00:45
Thanks, I reproduced the same problem.  I saw that in https://github.com/phetsims/beers-law-lab/issues/320#issuecomment-1412677589 (5 days ago) @zepumph and I collaborated to improve the locale initialization sequence.  It seems it would be better for fallbacks to work in the usual way even if assertions are enabled.  So I think we decided we no longer want the behavior listed in https://github.com/phetsims/phet-io/issues/1901#issuecomment-1401423861 (2 weeks ago). Sorry this wasn't clearly communicated.  Therefore, this issue can be closed.

**Comment by arouinfar** [comment] 2023-02-07 01:21
@samreid good to know. We should update phet-io-guide.md because it currently tells clients to expect an assertion.

Relevant section: https://github.com/phetsims/phet-io-sim-specific/blob/master/client-guide-common/client-guide/phet-io-guide.md#use-of-query-parameters-with-the-standard-phet-io-wrapper

> If you specify a locale for which a translation does not exist, two things may happen. If `phetioDebug=false`, the `locale` query parameter is ignored and the simulation will retain the `localeProperty` used when creating the Standard PhET-iO Wrapper. If `phetioDebug=true`, an assertion will be thrown.

**Comment by arouinfar** [comment] 2023-02-07 01:26
@samreid I updated master in the commit referenced above. The section now reads:

> If you specify a locale for which a translation does not exist, the `locale` query parameter is ignored and the simulation will retain the `localeProperty` used when creating the Standard PhET-iO Wrapper.

**Comment by matthew-blackman** [comment] 2023-02-07 17:32
Fixed and confirmed in rc.4. @arouinfar said that we can test this ourselves, so we are ready to go to production on that one.

**Comment by samreid** [comment] 2023-02-07 21:22
@matthew-blackman and I cherry-picked the change from @arouinfar into ph-scale and ph-scale basics, checked in the RCs and double checked in the production version. Closing.

**Closed by samreid** 2023-02-07 21:22 UTC
Labels: dev:phet-io, status:ready-to-cherry-pick
