### ISSUE TITLE
Studio doesn't "Preview Sim" properly when solute is not at half a liter

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ph-scale#223] opened 2021-07-13 20:03 UTC
For https://github.com/phetsims/qa/issues/669. Seems to have happened in the recent dev-lite as well (sorry for missing it).
Oddly, this only seems to happen in Studio, not (from what I can tell) the State wrapper.

When the sim is launched with a solution (mostly non-water) and the level is not .5L, the sim does not launch in the correct state. Water seems less impacted than other solutes. If the level is less than .5, the sim launches at .5L anyway. If it is more (either by adding water or by adding solute with the dropper) the sim launches with the dropper showing the pour animation, but with no fill actually occurring.

![nonhalfliter](https://user-images.githubusercontent.com/41024075/125517416-6cca6682-a7e0-4eeb-9476-1f90cd02f908.gif)

**Comment by pixelzoom** [comment] 2021-07-13 22:24
Steps to reproduce:

1. Start the sim in Studio
2. Go to the Macro screen
3. Select "Battery Acid" (or any solute) from the combo box
4. Wait for the beaker to autofill to 0.5L.
5. Drain a bit of solution, using the drain faucet.
6. Press the "Preview Sim" button.
7. The preview sim starts with the correct amount of solution, but immediately autofills to 0.5L.

**Comment by pixelzoom** [comment] 2021-07-13 22:25
Similar problem in the Micro screen, using the sanme steps to reproduce.

**Comment by pixelzoom** [comment] 2021-07-13 22:29
No problem in ph-scale-basics, if started with defaults.  But if I add `?autofill=true`, then it has the same problem as the Macro screen in ph-scale.  So probably related to `autofillEnabledProperty`.

**Comment by pixelzoom** [comment] 2021-07-13 22:38
Fixed in the above commit. @KatieWoe please verify in master. Then assign back to me so that I can patch the 1.5 branch.

**Comment by KatieWoe** [comment] 2021-07-13 22:45
Both seem fixed on master

**Comment by pixelzoom** [comment] 2021-07-13 22:52
🎉  Thanks @KatieWoe.  I'll proceed with patching the 1.5 branch.

**Comment by pixelzoom** [comment] 2021-07-13 23:07
Patches in 1.5 branches for ph-scale and ph-scale-basics, ready for testing in new RCs.

**Comment by Nancy-Salpepi** [comment] 2021-07-20 18:27
Emily and I just had issue #223 happen using state. I am using MacBook + safari and she is in Windows + firefox. 

Dropper showing pour animation 

Steps to Reproduce:
1. In state, select macro screen
2. Scroll down to the set state rate slider and set value to zero
3. In the upstream simulation, select battery acid (or any liquid)
4. Wait for the beaker to autofill to .5 L
5. Add either more of the battery acid or all of the liquid
6. Click the "Set State Now" button

<img width="625" alt="Screen Shot 2021-07-20 at 2 13 38 PM" src="https://user-images.githubusercontent.com/87318828/126375388-fa0c5cc9-6643-4e53-9ab3-0db8fed57a32.png">

Solution amount at half liter

Steps to reproduce:
1. In state, select macro screen
2. Scroll down to the set state rate slider and set value to zero
3. In the upstream simulation, select coffee(or any liquid)
4. Wait for the beaker to autofill to .5 L
5. Use drain faucet to remove some liquid
6. Click the "Set State Now" button

<img width="625" alt="Screen Shot 2021-07-20 at 2 14 04 PM" src="https://user-images.githubusercontent.com/87318828/126376094-deda2425-8b3d-4b7f-a028-1cdc212df5f2.png">

**Comment by pixelzoom** [comment] 2021-07-20 18:42
In [1.5.0-rc.1](https://phet-dev.colorado.edu/html/ph-scale/1.5.0-rc.1/phet-io/wrappers/state/), I've reproduced 2 problem using the steps shown in https://github.com/phetsims/ph-scale/issues/223#issuecomment-883604197.

In the first set of steps (for solution volume > 0.5L), after pressing "Set State Now",  the volume of the beaker is immediately correct in the downstream sim. But the dropper shows that it's autofilling - there is solute coming out of the dropper.

In the second set of steps (for solution volume < 0.5L), after pressing "Set State Now", the beaker autofills to 0.5L. This is the incorrect volume, and it should not autofill, it should immediate appear with the correct colume of solution

**Comment by pixelzoom** [comment] 2021-07-20 18:57
I verified that the 2 problems reported in https://github.com/phetsims/ph-scale/issues/223#issuecomment-883604197 do NOT occur in master or the 1.5 branch.  So no further work is needed, and this issue is still ready for verification in the next RC.

**Comment by Nancy-Salpepi** [comment] 2021-07-20 20:06
I just wanted to add that those 2 problems are also seen when the "Launch" button is pressed in State wrapper.

**Comment by pixelzoom** [comment] 2021-07-20 20:10
OK.  Self assigning to investigate whether the 1.5 patch that I've applied also addresses the "Launch" button in the State wrapper.

**Comment by pixelzoom** [comment] 2021-07-20 20:24
In [1.5.0-rc.1](https://phet-dev.colorado.edu/html/ph-scale/1.5.0-rc.1/phet-io/wrappers/state/), I've reproduced 2 problem with the "Launch" button in the State wrapper. 

In master and 1.5 branches, the problems are no longer occur.

So no further work is needed, and this issue is still ready for verification in the next RC.

**Comment by Nancy-Salpepi** [comment] 2021-07-26 14:00
I couldn't reproduce these issues in Studio or State. (MacBook 11.4 M1 chip + chrome)

**Closed by Nancy-Salpepi** 2021-07-26 14:00 UTC
Labels: dev:phet-io, status:ready-for-qa, type:bug
