### ISSUE TITLE
LoL Faucet shooter doesn't activate when clicked

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ph-scale#88] opened 2019-06-06 15:13 UTC
For https://github.com/phetsims/QA/issues/323
I noticed that when ph scale or ph scale basics is in the legends of learning harness the faucet shooter doesn't activate when briefly clicking on it.
In the normal versions of the sims, iframe, and xhtml, when you click (but don't hold) the shooter the faucet opens for a short time then closes.  When in the LoL harness this does not happen.  Most often there is not water at all, but sometimes a small stream does come out.  This seems to occur on chrome and not on firefox.
Steps:
1. Enter the sim in the LoL harness with the legendsOfLearning parameter
2. Go to a screen with a faucet shooter
3. Click on it but don't hold

![doesntopen](https://user-images.githubusercontent.com/41024075/59044278-1ba8b500-883b-11e9-9fb3-19cecf5ae943.gif)
![notatall](https://user-images.githubusercontent.com/41024075/59044280-1ba8b500-883b-11e9-9254-115dc8f73f62.gif)

**Comment by pixelzoom** [comment] 2019-06-06 18:49
@arouinfar  This seems like a bug that doesn't need to involve you, so feel free to self-unassign if you agree.

**Comment by arouinfar** [comment] 2019-06-06 18:56
@pixelzoom in the first .gif it looks like the volume of water increased by 0.01 L on the first click, but not on subsequent clicks.

**Comment by pixelzoom** [comment] 2019-06-15 22:00
I reproduced the problem as described. But have no idea why this is a problem only in the LoL Harness.  

@ariel-phet I will need some of @jonathanolson's time to investigate.  Please prioritize and assign.

**Comment by pixelzoom** [comment] 2019-06-17 01:26
In case this had something to do with running in an iframe, I tried [1.3.0-rc.1 ph-scale_en_iframe_phet.html ](https://bayes.colorado.edu/dev/html/ph-scale/1.3.0-rc.1/phet/ph-scale_en_iframe_phet.html).  It works fine, no problem.  So these seems specific to LoL.

**Comment by ariel-phet** [comment] 2019-06-18 17:34
@pixelzoom @KatieWoe the "working on tap" was added to give feedback to users that the faucet shooter is interactive in case they do not pull it out. Since this is only happening in the LoL harness and not a huge deal, I don't think it is worth fixing. Marking as `wontfix`

**Closed** 2019-06-18 17:35 UTC
Labels: type:bug, type:wontfix

**Comment by KatieWoe** [comment] 2019-07-23 22:52
Since this is marked as won't fix, there isn't really anything for QA to check
