### ISSUE TITLE
empty client guides published with this sim

### ISSUE THREAD

**Issue by zepumph** [phetsims/ph-scale#167] opened 2020-07-09 22:16 UTC
In https://phet-dev.colorado.edu/html/ph-scale/1.4.0-rc.1/phet-io/, there is a row in the table for the client guide and client request. Both of these are empty files (https://github.com/phetsims/phet-io-client-guides/tree/master/ph-scale)

Over in https://github.com/phetsims/phet-io-client-guides/issues/2 @chrisklus and I got rid of all client guides that were blank except for upcoming releases. I guess that I forgot that ph-scale was not going to use this new, md rendered client guide, and would instead just use google docs. @arouinfar is that true? If so, ph-scale (and likely ph-scale-basics) should have their folders removed from phet-io-client-guides/ before publication (and patched into the rc branch). 

* @arouinfar please confirm that there will not be phet-io-client-guides md files for ph-scale(-basics)
* a developer to remove these folders on master (simple commit)
* a developer (likely @pixelzoom) to patch this into rc branches accordingly.

**Comment by arouinfar** [comment] 2020-07-16 06:58
@zepumph we do not intend to deliver any more google docs to the client, and all documentation should go in this repo. The rc's for ph-scale and ph-scale-basics were published before I thought about the fact that their documentation still needs to be converted to md, but I will definitely have those files converted before rc testing wraps up.

**Comment by pixelzoom** [comment] 2020-07-16 15:10
@arouinfar Please let me know when the pH Scale doc have been converted, so that I can patch the 1.4 release branch.

**Comment by pixelzoom** [comment] 2020-07-21 23:28
@arouinfar said:
>...  I will definitely have those files converted before rc testing wraps up

If these are to be published with the RC, then they should be patched into the 1.4 branches before the final RC is delivered to QA for test.  And it's difficult to identify "the final RC" until after it's been tested.  

I'm also not clear on why @zepumph is assigned and @arouinfar is not, so assigning them both.

**Comment by arouinfar** [comment] 2020-07-21 23:39
I'm tracking client guide work in https://github.com/phetsims/phet-io-client-guides/issues/5

**Comment by zepumph** [comment] 2020-07-23 00:28
@arouinfar please assign @pixelzoom to this issue when phet-io-client-guides/ph-scale and phet-io-client-guides/ph-scale-basics are ready to be applied to the rc branch. @pixelzoom when that time comes, I would recommend pulling all, building both sims, and then spot checking two links in each wrapper index: "PhET-iO Guide" and "Client Requests". The main thing would be to make sure that there are no templated vars leaking into the build version, and the links are not broken. 

Unassigning. Let me know if I can help!

**Comment by arouinfar** [comment] 2020-07-29 06:05
I've finished converting the guides to .md, and phet-io-client-guides/ph-scale and phet-io-client-guides/ph-scale-basics are now ready to be applied to the rc branch @pixelzoom. The temporary pdf's still need to be deleted, but I'll leave those alone until QA is finished with this rc test.

**Comment by pixelzoom** [comment] 2020-07-29 19:32
@arouinfar I don't see any commits associated with this issue, so I don't know what to cherry-pick.  Please locate your commits in the GitHub UI, and label them with this issue number.

**Comment by arouinfar** [comment] 2020-07-29 20:31
Work was tracked in https://github.com/phetsims/phet-io-client-guides/issues/5, but I commented on the commits so they show up here too.

**Comment by pixelzoom** [comment] 2020-07-29 21:21
I made a couple of edits in the above commits, but overall these docs look great.

**Comment by pixelzoom** [comment] 2020-07-29 21:48
Changes have been cherry-picked.  Verified by viewing the ph-scale-1.4 and ph-scale-basics-1.4 branches of phet-io-client-guides.  To be regression tested in the next RC.

**Comment by pixelzoom** [comment] 2020-08-04 22:17
To test this in ph-scale 1.4.0-rc.2:

1. Go to the wrapper index at https://phet-dev.colorado.edu/html/ph-scale/1.4.0-rc.2/phet-io/
2. Verify that the "PhET-iO Guide" link works
3. Verify that the "Client Requests" link works

**Comment by pixelzoom** [comment] 2020-08-15 14:20
@arouinfar Looks like temper pdf (guides) were delete in https://github.com/phetsims/phet-io-client-guides/commit/5996b84d11dba871fed952f830b6ba9caef4b4d7 and https://github.com/phetsims/phet-io-client-guides/commit/12a7d03989f30605a4ea04ca561b89480e5172b0.  Are those the complete sets of commits?  They also need to be delete in the 1.4 branches.

**Comment by arouinfar** [comment] 2020-08-17 16:59
@pixelzoom it doesn't look like the .pdf's were ever in those branches. 

![image](https://user-images.githubusercontent.com/8419308/90422698-77deaa00-e078-11ea-8def-ca6a576f9e9d.png)
![image](https://user-images.githubusercontent.com/8419308/90422832-ac526600-e078-11ea-8811-f938be7b5da7.png)

**Comment by pixelzoom** [comment] 2020-08-17 17:33
OK, thanks @arouinfar.

**Comment by KatieWoe** [comment] 2021-05-12 19:42
Checked on Win 10 Chrome in 1.5.0-dev.1. Links work, closing

**Closed by KatieWoe** 2021-05-12 19:42 UTC
Labels: design:phet-io, status:ready-for-qa
