### ISSUE TITLE
autofill still occurs with invisible dropper

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/ph-scale#178] opened 2020-07-21 22:54 UTC
<b>Test Device</b>

Windows 10 Laptop

<b>Operating System</b>

Windows 10 v.1903

<b>Browser</b>

Chrome Version 84.0.4147.89

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/515 & https://github.com/phetsims/QA/issues/514

When the query parameter autoFill is set to true and the dropper is no longer visible via Studio, the filling animation still occurs as if the dropper was visible.

<b>Visuals</b>

![2020-07-21PHScleBasicPhetIODropperfill](https://user-images.githubusercontent.com/54685448/88115071-8cf81400-cb72-11ea-96fd-0cf131cc3779.gif)

**Comment by pixelzoom** [comment] 2020-07-21 23:20
I don't see anything in the Client Guide that asks to be able to hide the dropper.   So the easy solution to this is to make `dropperNode.visibleProperty` read-only.   

The more involved solution is to autofill only if the dropper is visible.  Autofill is handled in the model, so this would involve add a new phet-io-only Property, `dropperVisibleProperty`, in the model, have it control the visibility of the dropper view, and make`dropperNode.visibleProperty` read-only.  

@arouinfar how do you want to proceed?

**Comment by arouinfar** [comment] 2020-07-22 17:37
Nice find @KatieWoe.

> I don't see anything in the Client Guide that asks to be able to hide the dropper. So the easy solution to this is to make `dropperNode.visibleProperty` read-only. 

That sounds like a perfect solution to me @pixelzoom. Let's do it.

I don't think we need to complicate things with the `dropperVisibleProperty`, though it's good to know there's a potential solution if a future client insists on being able to hide the DropperNode.

**Comment by pixelzoom** [comment] 2020-07-22 18:19
`dropperNode.visibleProperty` is now read-only.   Committed to master, patched into 1.4 branches of ph-scale and ph-scale-basics.  To be regression tested in new RC.

**Comment by pixelzoom** [comment] 2020-08-04 21:53
To verify in ph-scale 1.4.0-rc.2:

1. Run the sim in Studio
2. Verify that `phScale.macroScreen.view.dropperNode.visibleProperty` and `phScale.microScreen.view.dropperNode.visibleProperty` are read-only.

**Comment by brooklynlash** [comment] 2021-05-12 20:52
Instead of it being read-only, it does not even seem to exist on Chromebook. Not sure if this is intended or not.

**Comment by loganbraywork** [comment] 2021-05-12 21:02
As far as Windows Chrome and Firefox go, I can see both phScale.microScreen.view.dropperNode.visibleProperty & phScale.macroScreen.view.dropperNode.visibleProperty as read only, so it seems fixed to me

**Comment by liam-mulhall** [comment] 2021-05-12 21:25
`phScale.microScreen.view.dropperNode.visibleProperty` is read only on macOS.

**Comment by pixelzoom** [comment] 2021-05-12 21:47
@brooklynlash said:
> Instead of it being read-only, it does not even seem to exist on Chromebook. Not sure if this is intended or not.

@brooklynlash Did you have "PhET-iO Elements" set to "All" or "Features"?  This is not a featured element, so you'll need to select the "All" radio button, as shown in the screenshot below.  Please verify whether that fixes the problem.  And apologies that this was not specified in the instructions in https://github.com/phetsims/ph-scale/issues/178#issuecomment-668843435, I've updated them.

![screenshot_980](https://user-images.githubusercontent.com/3046552/118048275-465deb00-b339-11eb-8b8f-df10c8b1c82c.jpg)

**Comment by brooklynlash** [comment] 2021-05-12 22:12
Yes, my mistake again. I see it now, thank you.

**Comment by pixelzoom** [comment] 2021-05-12 22:22
Excellent, thanks @brooklynlash.

Closing.

**Comment by arouinfar** [comment] 2021-05-20 04:31
@kathy-phet saw this issue and messaged me on Slack:
> I can think of a reason a client might want to do that - if they want to create something really focused on dilution and not have the dropper node visible - since that complicates when you add back into the solution. So I think I would lean to adding this visible property to control that if its not too much work for CM? What do you think about this potential use ...?

I hadn't previously thought of this use case, but @kathy-phet makes a good point. Hiding the dropper would be useful in a lesson focused on dilution. I would recommend that we revert this change and make `dropperNode.visibleProperty` phetioReadOnly: false. 

This means that autofill will occur through an invisible dropper, so we should decide what (if anything) to do. Some options include: 
(1) Do nothing, but document the issue in the client guide. If clients want to hide the dropper, they should not switch solutes.
(2) Keep autofill, but hide the stream dispensed from the dropper.
(3) Disable autofill. Switching solutes will result in a pre-filled beaker.

I would be fine with any of these options. @pixelzoom what would you recommend?

**Comment by pixelzoom** [comment] 2021-05-20 18:01
(1) requires no work.

(2) is significantly easier than (3).

Let me know how you want to proceed.

**Comment by arouinfar** [comment] 2021-05-21 22:37
@pixelzoom let's proceed with (2). It prevents us from telling users, "if you do X, you also have to do Y".

**Comment by pixelzoom** [comment] 2021-05-24 18:07
@arouinfar Question: In ph-scale-basics, the default is `autofill: false`.  So if you make the dropper invisible, nothing will happen when you switch solutes via the combo box.  The client would have to know to start the sim with `autofill: true`, or change `phScaleBasics.macroScreen.model.autofillEnabledProperty`.   Is this OK?  

Or should the autofill setting be ignored when the dropper is made invisible, and always autofill?  This seems a little more complicated to describe, and potentially confusing.

Either way, something about this probably needs to be added to the Client Guide for ph-scale and ph-scale-basics.

**Comment by pixelzoom** [comment] 2021-05-24 19:03
In the above commit, I added `model.dropper.visibleProperty`, which is linked to `view.dropperNode.visibleProperty` and the `dropperFluidNode` (which is internal, and not instrumented).  So if you set `model.dropper.visibleProperty`, the dropper and the fluid that comes out of the dropper will be hidden. @arouinfar please verify in master.

@arouinfar and I discussed https://github.com/phetsims/ph-scale/issues/178#issuecomment-847232990 via Zoom, and agreed that ignoring autofill setting could be confusing.  So @arouinfar will add appropriate info to the Client Guides for ph-scale and ph-scale-basics, indicating that autofill should be enabled if you're going to hide the dropper.

**Comment by arouinfar** [comment] 2021-05-24 20:39
@pixelzoom the behavior looks good in master. I've edited the client guides in the above commits, so closing.

**Closed by arouinfar** 2021-05-24 20:39 UTC
Labels: design:phet-io, status:blocks-sim-publication, status:ready-for-review
