### ISSUE TITLE
fix for query-string-machine localStorage issue

### ISSUE THREAD

**Issue by samreid** [phetsims/ph-scale#89] opened 2019-07-17 05:57 UTC
As part of https://github.com/phetsims/query-string-machine/issues/34 @chrisklus and I applied a query-string-machine fix to many sims, but not to ph-scale or ph-scale-basics, which already have RC SHAs.  In short, we need a try/catch around the local storage.  

buggy sha
570fe1febbd045d44b9d6d88433a7f8a9d84a1d6

fixed sha
1f64976a20ac1cf35c91c560f5e33df474eceec5

See discussion in https://github.com/phetsims/query-string-machine/issues/34#issuecomment-512094196

We later learned from @jonathanolson and the process itself that the maintenance release process skips creating RCs for unpublished sim/branch combinations, so the next time we face a similar problem we can include all affected sim/branch combinations without trying to prune them.

When ph-scale and ph-scale-basics are published, they should have the try/catch.  @pixelzoom if you would like assistance upgrading to the fixed sha in Query String Machine, please let me or @chrisklus know.

**Comment by pixelzoom** [comment] 2019-07-17 15:04
ph-scale and ph-scale-basics were excluded because it's in the middle of QA testing, and we didn't want to generate a bogus RC.  Apparently that would not happen with the maintenance release process, but that wasn't known until after the maintenance release had been done.   So @samreid and/or @chrisklus are going to apply the patch to ph-scale and ph-scale-basics.

<details>
<summary>Slack discussion</summary>

Sam Reid:house_with_garden: 9:35 PM
@chrisklus and I are starting a maintenance release process to address https://github.com/phetsims/query-string-machine/issues/34.  Please do not make changes to any release branch until we give the go-ahead.

Chris Malley 9:36 PM
Will that include unpublished release branches?

Sam Reid:house_with_garden: 9:39 PM
In https://github.com/phetsims/query-string-machine/issues/34#issuecomment-512087941 we identified 4 published release branches with the symptom and 11 (unreleased) release branches.  We thought it would be best to patch them all. (edited) 

Do you concur?

Chris Malley 9:40 PM
I’m not familiar with the issue.  I was wondering mainly about pH Scale and pH Scale: Basics, which are both in the RC test phase on unpublished release branches.

Looks like they are in your list.

Sam Reid:house_with_garden: 9:43 PM
So will this process publish new RCs?

Chris Malley 9:53 PM
I would think that you don’t want to publish RCs for unpublished release branches.  I’d prefer not for pH Scale & pH Scale: Basics, because there is still work to be done before the next RC.   If you have to publish, I’ll just skip the version that you publish, and live with the discontinuity in RC version numbering. (edited) 

Sam Reid:house_with_garden: 10:00 PM
I’m not understanding the problem.  ph-scale 1.3 branch will still need the fix.  Are you requesting us to skip it so you can do it yourself later?

Or are you saying you want all of the problems identified in ph-scale 1.3.0-rc.1 to be fixed in ph-scale 1.3.0-rc.2 (including this problem)?

Sam Reid:house_with_garden: 10:08 PM
After discussion, @chrisklus and I agreed we should go forward with patching this for as many branches as we can.  We will manually remove ph-scale and ph-scale-basics so that @pixelzoom may apply the patch as part of his release candidate process.

Chris Malley 10:27 PM
I am not familiar with the issue,  I am likely to forget, and I don’t need another task. So by all means, go ahead and patch.  I’ll ignore the RC and explain to QA.  Seems like other “in progress” RCs would have the same problem with having an RC published for the patch. And I don’t know why patching necessitates publishing an RC for unreleased branches.  But the batch patching process is a mystery to me (and I’d like to keep it that way :) (edited) 

To answer your questions above…  I was hoping you could patch the problem, but not publish an RC.

Chris Malley 10:36 PM
To clarify further…  If patching this issue automatically publishes pH Scale 1.3.0-rc.2, that RC may be suitable for testing the patch, but it is not a release candidate.  There are other outstanding issues that are in the process of being fixed, and when those issues have been addressed, then it will be appropriate to publish an actual release candidate.

Sam Reid:house_with_garden: 10:42 PM
Good point, thanks for bringing it up.  I asked @jonathanolson
We have a question.  We applied fixes to some unpublished branches.  The maintenance release process will create RCs for them.  We do not want those to be published at the end, because they are still, say, in RC testing.  How do we deal with this?

Jonathan Olson:house_with_garden: 11:41 PM
It should detected certain release branches as unpublished, so these will NOT be included in any deployments

Sam Reid:house_with_garden: 11:41 PM
Perfect, we are seeing that.  Thanks!

Jonathan Olson:house_with_garden: 11:42 PM
Is there a way that can be highlighted more (in the prompt) or documented better?

Sam Reid: 11:45 PM
Documentation for step 12 currently says:
> Running Maintenance.deployReleaseCandidates() will deploy release-candidate versions for any release branches that have maintenance changes since the last deploy (it won’t needlessly deploy RCs for branches that didn’t change). Like normal rc deploys, you will need to be on campus or on vpn for this process.
Perhaps it should also say it only creates RCs for published versions? (edite

Chris Malley 8:55 AM
So if it only creates RCs for published versions, why weren’t ph-scale and ph-scale-basics included in the maintenance release? https://github.com/phetsims/ph-scale/issues/89

new messages
Sam Reid:house_with_garden: 8:59 AM
None of the 3 people working on the process were aware of that fact until after the fact.  In prior comments, it was recommended to revise the documentation to improve this for the future.  Would you like us to patch those branches?  We are happy to do so.
Chris Malley 9:01 AM
Thanks for the clarification. Please do apply the patch — I’m not familiar with the issue, and don’t have time to become familiar with the issue, so it will be more efficient if you or CK handle it.  Thanks.

</summary>

**Comment by pixelzoom** [comment] 2019-07-17 15:06
Please label this issue as "fixed-awaiting-deploy" after the patch has been applied, so that I can include it in the list of issues to test for 1.3.0-rc.2.

**Comment by samreid** [comment] 2019-07-18 04:38
Here are the commands I used to apply query-string-machine patches for these sims:

```
cd ../perennial/
grunt checkout-target --repo=ph-scale --target=1.3
cd ../query-string-machine/
git checkout -b ph-scale-1.3
git cherry-pick 1f64976a20ac1cf35c91c560f5e33df474eceec5
git push origin ph-scale-1.3
cd ../ph-scale
grunt
cp build/phet/dependencies.json .
git add dependencies.json
git commit -m "update shas for fix in https://github.com/phetsims/ph-scale/issues/89"
git push origin 1.3

cd ../perennial/
grunt checkout-target --repo=ph-scale-basics --target=1.3
cd ../query-string-machine/
git checkout -b ph-scale-basics-1.3
git cherry-pick 1f64976a20ac1cf35c91c560f5e33df474eceec5
git push origin ph-scale-basics-1.3
cd ../ph-scale-basics
grunt
cp build/phet/dependencies.json .
git add dependencies.json
git commit -m "update shas for fix in https://github.com/phetsims/ph-scale/issues/89"
git push origin 1.3
```

**Comment by samreid** [comment] 2019-07-18 04:45
To test the changes, I opened the built versions in the browser and saw they launched correctly.  I also manually inspected the debug versions to make sure the localStorage access was wrapped with try/catch.  I also ran `grunt checkout-shas` for each of the sims and made sure the fix was in the query-string-machine repo SHA.  Labeling as prescribed in https://github.com/phetsims/ph-scale/issues/89#issuecomment-512296544 but also adding @pixelzoom as an assignee in case there's anything else he wants to cross-check for these changes.

**Comment by pixelzoom** [comment] 2019-07-23 16:59
@KatieWoe I'm not familiar with this issue - it was a general patch that was applied to many sims.  If you have question about how to test, please ask @samreid.

**Comment by samreid** [comment] 2019-07-23 17:16
For the batch maintenance release, @chrisklus and I tested by (a) manually inspecting the code to make sure it had the fix and (b) having @ariel-phet confirm the sims opened properly in the Android app.  I do not know of a way to test unpublished sims or RCs in the Android app (I know this is not yet possible for the iOS app).  So for pH scale and pH scale basics, steps (a) and (b) may again be sufficient.  Step (a) was completed in https://github.com/phetsims/ph-scale/issues/89#issuecomment-512662945.  So one way to verify this would be to wait until the sim is published, then make sure it opens properly in the Android app.

Assigning @ariel-phet for comment since he knows more about the Android app.  Is there a better way to verify?  Or is post-publication verification as we did for https://github.com/phetsims/query-string-machine/issues/34 sufficient?

**Comment by ariel-phet** [comment] 2019-07-23 23:46
@pixelzoo @KatieWoe, yes @samreid is correct, there is currently no way except post-publication to test the sim in the app to make sure this bug is not present. This patch was pretty minor and low risk as it only affected a small amount of code, and given the sims that already work with the patch, I have a high confidence it is fine.

We will be looking into how to test RC versions within both apps, but given that it is not yet possible, I think it is reasonable to close this issue as it has been confirmed on several sims.

**Closed by ariel-phet** 2019-07-23 23:46 UTC
Labels: status:ready-for-qa, type:bug
