### ISSUE TITLE
Usability on small screens review

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ph-scale#78] opened 2019-04-18 18:29 UTC
Per @kathy-phet's request in https://github.com/phetsims/QA/issues/295 I am making issues in each published sim repo detailing the pointer areas and usability of sims on phone sized screens.  Done on an iPhone 7 iOS 12 device.

Potential Difficulties Noticed:
* See https://github.com/phetsims/scenery-phet/issues/488#issuecomment-484628604

Screenshots:
![Image from iOS (1)](https://user-images.githubusercontent.com/41024075/56382781-6c097c00-61d5-11e9-8d87-7a10ab6ef426.png)
![Image from iOS (2)](https://user-images.githubusercontent.com/41024075/56382782-6c097c00-61d5-11e9-84c3-bb9f8bbfd6eb.png)
![Image from iOS (3)](https://user-images.githubusercontent.com/41024075/56382783-6ca21280-61d5-11e9-895b-e1bbfdc22dd6.png)
![Image from iOS](https://user-images.githubusercontent.com/41024075/56382784-6ca21280-61d5-11e9-9b08-fe0146a4c7f0.png)

**Comment by arouinfar** [comment] 2019-04-18 18:34
This appears to be a duplicate of #77, closing.

**Closed by arouinfar** 2019-04-18 18:34 UTC
