### ISSUE TITLE
Launched sims may not fill/empty properly

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ph-scale#156] opened 2020-03-31 16:45 UTC
**Device**
Dell
**OS**
Win 10
**Browser**
Chrome 80.0.3987.149
**Problem Description**
For https://github.com/phetsims/QA/issues/487. Phet-io
In studio, if you have altered the liquid level, then the sim launched will not be able to drain or fill at all. Switching solution will cause the dropper to always look like it is filling (When beaker was over half full), with the liquid level staying the same. Trying to use either faucets or the dropper gives the animation of liquid pouring, but no change in the beaker. If no change was made to the default liquid level before launch, this doesn't seem to occur.
**Steps to Reproduce**
1. Go to Studio
2. Go to either the first or second screen
3. Fill the beaker a bit more with faucet
4. press the Launch button in Studio
5. Try to alter liquid level in the launched sim

**Visuals**
![liquidfill](https://user-images.githubusercontent.com/41024075/78052483-6cdee380-733c-11ea-9e3e-a644366da0d7.gif)

**Comment by KatieWoe** [comment] 2020-03-31 16:53
Seems a bit more complicated. The dropper does work _if_ the beaker starts less than .5 L and once it reaches .5 L the sim seems to behave normally until reset all is used.

**Comment by pixelzoom** [comment] 2020-03-31 17:56
I've reproduced the steps described in https://github.com/phetsims/ph-scale/issues/156#issue-591258494.

@KatieWoe I cannot reproduce what you described in https://github.com/phetsims/ph-scale/issues/156#issuecomment-606747820.  Please provide specific steps.

**Comment by pixelzoom** [comment] 2020-03-31 17:58
@KatieWoe also please provide specific browser version.  In general, issues should also indicate the specific browser version number.   Things like "Chrome" or "Chrome latest" don't verify that we're all on the same page, especially if an issue isn't worked on for awhile.

**Comment by pixelzoom** [comment] 2020-03-31 20:16
Discussed https://github.com/phetsims/ph-scale/issues/156#issuecomment-606747820 with @KatieWoe on Zoom.  The steps are:

1. Go to Studio
2. Go to either the first or second screen
3. Drain the beaker a little
4. Lauch
5. Dropper works, but faucets do not.
6. Once you fill the beaker to 0.5L with the dropper, the dropper stops. 
7. Now the dropper, faucets, and solute combo box all work.
8. Press Reset All and everything will be back to the initial broken state when first launched.

So the sim is a bit more broken (or maybe broken in a different way) if you start by filling the beaker vs draining the beaker.

**Comment by pixelzoom** [comment] 2020-03-31 21:48
There is no similar problem (that I can detect) in the State Wrapper.  So I'm guess this has something to do the initial state being bad, maybe something important missing?  Beyond that, I have no idea what might be wrong, or how to troubleshoot.  I'll poke around a bit more before asking the IO team for assistance.

**Comment by pixelzoom** [comment] 2020-04-03 21:23
More detailed version of the steps that @KatieWoe reported in https://github.com/phetsims/ph-scale/issues/156#issue-591258494:

1. Go to Studio
2. Go to either the first or second screen
3. Add a little water to the beaker
4. Press the "Lauch" button in Studio.
5. Faucets and dropper do not work.
6. Changing solute immediately changes the solution, no auto-fill happens, volume stays the same.
7. Pressing Reset All button returns to to the same initial broken state.

**Comment by pixelzoom** [comment] 2020-04-06 22:04
I'm stump, and I have no idea how to even begin debugging this.  The launched sim opens in a new window (as a popup?) with no URL.   It prints a never-ending stream of messages to the console.  I have no idea if this stream can be filtered, what I can inspect, or how I can inspect it.

Suggesting from the iO team on how to proceed? @samreid @zepumph @chrisklus

**Comment by KatieWoe** [comment] 2020-04-06 22:06
May be related, but something I just noticed, if the initial setting is changed from water to something else, then the launched sim will not show the dropper animation for a new solution when it is selected.

**Comment by pixelzoom** [comment] 2020-04-06 22:09
Thanks @KatieWoe. I noted that in step 6 above, "auto-fill does not happen":

> 6. Changing solute immediately changes the solution, volume is unchanged, auto-fill does not happen, dropper is stuck in dispensing state, both faucets are disabled.

**Comment by KatieWoe** [comment] 2020-04-06 22:40
This does happen in State if you click the Launch button at the bottom (feel a bit silly for not thinking of that).

**Comment by pixelzoom** [comment] 2020-04-06 22:51
@samreid had the hypothesis that this might be related to auto-fill, and that was indeed the case.  

The model has `isAutoFillingProperty`, which controls whether the beaker is being automatically filled with the selected solute.  That Property was not instrumented because it was previously identified as unnecessary to instrument.   But not instrumenting `isAutoFillingProperty` causes problems when state is restored for the launched sim.  The sim starts, thinks it's autofilling, PhET-iO restores state, and the model gets all kinds of confused. 

So `isAutoFillingProperty` must be instrumented, and that's done in the above commit.  

@arouinfar @kathy-phet FYI, here's how it's instrumented:

```js
    // @public (read-only)
    this.isAutoFillingProperty = new BooleanProperty( false, {
      tandem: tandem.createTandem( 'isAutoFillingProperty' ),
      phetioReadOnly: true,
      phetioDocumentation: 'whether the beaker is in the process of being automatically filled with solute'
    } );
```

@KatieWoe please verify in master.

**Comment by KatieWoe** [comment] 2020-04-07 16:05
The bug looks fixed in master. I did notice that, when you switch liquids, the dropper animation plays, but it fills to .5 L, regardless of what the original state's level was. If this is acceptable, then this can probably be closed if you desire @pixelzoom

**Comment by pixelzoom** [comment] 2020-04-07 18:46
Thanks @KatieWoe.  

Yes, the expected behavior is that changing the solute auto-fills to 0.5L, not the previous liter of the solution.  This assures that you always have room to dilute the solution.  This is as it has been since the original Java version.

Closing.

**Closed by pixelzoom** 2020-04-07 18:46 UTC
Labels: dev:phet-io, status:ready-for-review, type:bug

**Comment by KatieWoe** [comment] 2020-04-07 18:48
To be clear, I don't mean the last amount. I mean the new starting point.

**Comment by pixelzoom** [comment] 2020-04-07 18:56
Thanks for clarifying - you mean the new initial state of the launched sim.   That does not (and should not) affect the behavior of auto-fill.  The auto-fill volume is always 0.5, regardless of the prior state of the solution.

**Comment by pixelzoom** [comment] 2020-04-07 18:59
And btw... Auto-fill is off in the ph-scale-basics sim, and can be turned off in ph-scale via `?autoFill=false`.   So the initial volume of the solution (when the sim starts) is in no way related to the auto-fill volume.   No one has asked for control of the auto-fill volume, but that would likely be done via yet-another query parameter.
