### ISSUE TITLE
Can't drag dropper while it dispenses

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ph-scale#86] opened 2019-05-30 22:45 UTC
**Test device:**
Dell
**Operating System:**
Win 10 (or any)
**Browser:**
chrome (or any)
**Problem description:**
For https://github.com/phetsims/QA/issues/323 and https://github.com/phetsims/QA/issues/326.
In the published version of the sim you can activate the dropper and drag it around at the same time.  You can do this with both the mouse and touch.  In the rc, you can't drag the dropper while it is active with the mouse, but you can with touch.  Nothing major, but it seems like an odd inconstancy.
**Steps to reproduce:**
1. Go to a screen with a dropper
2. Use the mouse to push and hold the button that starts the dropper
3. While dispensing, try to move the dropper left and right.

**Screenshots:**
![cantdrag](https://user-images.githubusercontent.com/41024075/58669728-32f71800-82fa-11e9-8a9a-02ef27abd0fd.gif)

Troubleshooting information (do not edit):

<details>

Name: ‪pH Scale: Basics‬
URL: https://phet-dev.colorado.edu/html/ph-scale-basics/1.3.0-rc.1/phet/ph-scale-basics_all_phet.html
Version: 1.3.0-rc.1 2019-05-24 13:37:56 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment] 2019-06-03 15:48
Reproduced with macOS 10.14.5 + Chrome latest, and it doesn't seem to be platform specific.  

The implementation of PHDropperNode has not changed.   My guess is the the toggle button on EyeDropperNode has new-style input listener that is behaving differently and causing the drag listener not to get events.  I'll need @jonathanolson's help on this.

**Comment by jonathanolson** [comment] 2019-06-03 16:10
If the combo box background should block clicks, presumably it should have `pickable:true`?

**Comment by jonathanolson** [comment] 2019-06-03 21:16
The problem is that most drag/button listeners are set up so that they "attach" to the pointer, locking out other drag/button listeners from starting the interaction. This looks like a case where we want to enable that (e.g. to press `attach:false` to the button's PressListener).

There was no supported way to pass listeners to the created PressListener for buttons, so I added `listenerOptions`, and then added the flag in EyeDropperNode.

@pixelzoom can you test/review?

**Comment by pixelzoom** [comment] 2019-06-15 20:52
Looks like this is working in master. @KatieWoe please verify, change to "fixed-awaiting-deploy" if it looks OK.

**Comment by KatieWoe** [comment] 2019-06-17 14:55
This looks good on master

**Comment by pixelzoom** [comment] 2019-06-17 15:09
Next step is to pick up this change in a "ph-scale-1.3" branch of scenery-phet.

**Comment by pixelzoom** [comment] 2019-06-17 16:41
Patched for 1.3 branches, ready to test in upcoming 1.3.0-rc.2.

**Comment by pixelzoom** [comment] 2019-07-22 18:07
Talked with @jonathanolson.  I should also create and patch "ph-scale-basics-1.3" branches for scenery-phet and sun.

**Comment by pixelzoom** [comment] 2019-07-23 16:41
Manually patched in "ph-scale-basics-1.3" branches for scenery-phet and sun.

**Comment by pixelzoom** [comment] 2019-07-29 16:42
Verified by QA in https://github.com/phetsims/QA/issues/374 and https://github.com/phetsims/QA/issues/375, closing.

**Closed by pixelzoom** 2019-07-29 16:42 UTC
Labels: status:ready-for-qa, type:bug
